"""
Generated Code for Operation: titanic_load
Code Type: data_loading
Generated at: 2025-06-09T01:00:28.983698

This code was automatically generated by the Advanced Data Science MCP Server.
You can run this code independently in your Python environment.
"""


import pandas as pd
import numpy as np

# Original file info: 0.1MB, 1310 rows

# Load full dataset (no sampling needed)
df = pd.read_csv('C:\langfuse\cherry\sandbox\datasets\titanic.csv')

print("Dataset loading completed!")
print(f"Final dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
